### ISSUE TITLE
The example script prints an error

### ISSUE THREAD

**Issue by jeongmincha** [halessi/DCF#1]
![image](https://user-images.githubusercontent.com/4997737/91159298-d8b65400-e702-11ea-8e8c-660e1cdc81fe.png)

Your example script does not work :( 
```
$ python main.py --t AAPL --i 'quarter' --y 3 --eg .15 --steps 2 --s 0.1 --v eg
```

**Comment by halessi** [comment]
hi, thanks for commenting. I haven't updated this repository in a while...this error is probably because of the API changing the formatting of their responses to queries. 

if you want to adjust get_income_statement so it properly grabs the financials and make a pull request, that would be great. otherwise, I am not sure when I'll fix this. sorry. the difficult of adjusting get_income_statement will depend upon how much the formatting has been changed.
